-- Generated by scripts/generate-seed.js. Safe to re-run.
alter table products add column if not exists tag text;
alter table products add column if not exists rating numeric(2,1);
alter table products add column if not exists reviews integer default 0;

alter table orders add column if not exists phone_number text;
alter table orders add column if not exists payment_method text default 'Pay on Delivery';

insert into products (id, name, category, price, image_url, description, sizes, tag, rating, reviews) values
('wz-001', 'Adire Graphic Tee', 'Men', 58, 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80', 'Heavyweight organic cotton tee with a hand-printed Adire motif.', '["S","M","L","XL","XXL"]'::jsonb, 'BESTSELLER', 4.9, 128),
('wz-002', 'Sahara Graphic Tee', 'Men', 54, 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80', 'Boxy terracotta tee with a quiet back print.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.6, 71),
('wz-003', 'Linen Kimono Shirt', 'Men', 112, 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=80', 'Open-weave linen kimono shirt with a relaxed, drapey fit.', '["S","M","L","XL","XXL"]'::jsonb, 'NEW', 4.8, 46),
('wz-004', 'Ankara Bomber Jacket', 'Men', 218, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80', 'Quilted bomber finished in a limited Ankara print.', '["S","M","L","XL","XXL"]'::jsonb, 'LIMITED', 4.9, 39),
('wz-005', 'Corduroy Overshirt', 'Men', 134, 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=900&q=80', 'Mid-wale corduroy overshirt in warm sand.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.7, 88),
('wz-006', 'Tailored Wool Trousers', 'Men', 156, 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=900&q=80', 'Pleated wool-blend trousers with a clean, tapered leg.', '["S","M","L","XL","XXL"]'::jsonb, 'BESTSELLER', 4.8, 102),
('wz-007', 'Safari Jacket', 'Men', 189, 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80', 'Four-pocket cotton-twill safari jacket with a belted waist.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.6, 54),
('wz-008', 'Agbada Kaftan', 'Men', 142, 'https://images.unsplash.com/photo-1583496661160-fb5886a13d77?auto=format&fit=crop&w=900&q=80', 'Lightweight cotton kaftan with minimal embroidered neckline.', '["S","M","L","XL","XXL"]'::jsonb, 'NEW', 4.8, 33),
('wz-009', 'Utility Cargo Pants', 'Men', 118, 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=900&q=80', 'Relaxed cargo pants cut from washed cotton canvas.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.5, 77),
('wz-010', 'Heavyweight Hoodie', 'Men', 98, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80', '480gsm brushed-back fleece hoodie in earthy charcoal.', '["S","M","L","XL","XXL"]'::jsonb, 'BESTSELLER', 4.9, 214),
('wz-011', 'Indigo Adire Shirt', 'Men', 96, 'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?auto=format&fit=crop&w=900&q=80', 'Short-sleeve camp shirt in hand-dyed indigo Adire.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.4, 29),
('wz-012', 'Pleated Linen Shorts', 'Men', 74, 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=900&q=80', 'Easy pleated shorts in breathable stone linen.', '["S","M","L","XL","XXL"]'::jsonb, 'NEW', 4.5, 41),
('wz-013', 'Structured Midi Dress', 'Women', 176, 'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80', 'Sculpted midi dress with a defined waist and cap sleeve.', '["S","M","L","XL","XXL"]'::jsonb, 'BESTSELLER', 4.9, 156),
('wz-014', 'Silk Wrap Top', 'Women', 108, 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80', 'Fluid silk wrap top with a self-tie closure.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.7, 63),
('wz-015', 'Pleated Palazzo Pants', 'Women', 124, 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80', 'High-waisted palazzo pants with knife pleats.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.8, 92),
('wz-016', 'Belted Trench Coat', 'Women', 248, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80', 'Water-resistant cotton trench with storm flap detailing.', '["S","M","L","XL","XXL"]'::jsonb, 'LIMITED', 4.9, 58),
('wz-017', 'Cropped Linen Blazer', 'Women', 164, 'https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?auto=format&fit=crop&w=900&q=80', 'Boxy cropped blazer in structured Belgian linen.', '["S","M","L","XL","XXL"]'::jsonb, 'NEW', 4.7, 47),
('wz-018', 'Halter Maxi Dress', 'Women', 168, 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80', 'Backless halter maxi in a fluid crepe.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.8, 84),
('wz-019', 'Asymmetric Tunic', 'Women', 118, 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?auto=format&fit=crop&w=900&q=80', 'Asymmetric-hem tunic with a sculptural collar.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.5, 36),
('wz-020', 'Wide-Leg Jumpsuit', 'Women', 192, 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=80', 'One-piece wide-leg jumpsuit with an adjustable belt.', '["S","M","L","XL","XXL"]'::jsonb, 'BESTSELLER', 4.8, 119),
('wz-021', 'Ribbed Knit Skirt', 'Women', 88, 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80', 'Stretch ribbed midi skirt that hugs and moves.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.6, 70),
('wz-022', 'Ankara Wrap Dress', 'Women', 164, 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=900&q=80', 'Geometric Ankara print wrap dress with a flowing hem.', '["S","M","L","XL","XXL"]'::jsonb, 'NEW', 4.9, 52),
('wz-023', 'Satin Slip Skirt', 'Women', 92, 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=80', 'Bias-cut satin slip skirt in warm champagne.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.4, 45),
('wz-024', 'Linen Shirt Dress', 'Women', 138, 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80', 'Relaxed linen shirt dress with a drop shoulder.', '["S","M","L","XL","XXL"]'::jsonb, null, 4.6, 61),
('wz-025', 'Leather Crossbody Bag', 'Accessories', 168, 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=900&q=80', 'Vegetable-tanned leather crossbody with brass hardware.', '["One Size"]'::jsonb, 'BESTSELLER', 4.9, 173),
('wz-026', 'Woven Bucket Hat', 'Accessories', 52, 'https://images.unsplash.com/photo-1520975916090-3105956dac38?auto=format&fit=crop&w=900&q=80', 'Hand-woven raffia bucket hat.', '["S","M","L"]'::jsonb, null, 4.5, 38),
('wz-027', 'Minimalist Wool Scarf', 'Accessories', 78, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80', 'Oversized merino scarf in a tonal weave.', '["One Size"]'::jsonb, 'NEW', 4.7, 49),
('wz-028', 'Canvas Weekend Tote', 'Accessories', 86, 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80', 'Heavy canvas tote with leather handles.', '["One Size"]'::jsonb, null, 4.8, 96),
('wz-029', 'Beaded Bracelet Set', 'Accessories', 46, 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=900&q=80', 'Hand-beaded stacking bracelets, set of three.', '["One Size"]'::jsonb, 'LIMITED', 4.8, 64),
('wz-030', 'Suede Chelsea Boots', 'Accessories', 228, 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=900&q=80', 'Italian suede Chelsea boots with a stacked sole.', '["S","M","L","XL","XXL"]'::jsonb, 'BESTSELLER', 4.9, 141),
('wz-031', 'Leather Belt', 'Accessories', 64, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=80', 'Full-grain leather belt with a solid brass buckle.', '["S","M","L"]'::jsonb, null, 4.6, 52),
('wz-032', 'Raffia Sun Hat', 'Accessories', 58, 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80', 'Wide-brim raffia hat for sun-drenched days.', '["S","M","L"]'::jsonb, null, 4.4, 31),
('wz-033', 'Brass Cuff', 'Accessories', 68, 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=900&q=80', 'Hand-hammered brass cuff with a matte finish.', '["One Size"]'::jsonb, 'NEW', 4.7, 27),
('wz-034', 'Silk Headwrap', 'Accessories', 48, 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=80', 'Printed silk headwrap that doubles as a scarf.', '["One Size"]'::jsonb, null, 4.6, 44),
('wz-035', 'Leather Card Holder', 'Accessories', 42, 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=80', 'Slim leather card holder in cognac.', '["One Size"]'::jsonb, null, 4.7, 83),
('wz-036', 'Woven Market Basket', 'Accessories', 72, 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=80', 'Hand-woven market basket with leather straps.', '["One Size"]'::jsonb, null, 4.5, 35)
on conflict (id) do update set
  name = excluded.name, category = excluded.category, price = excluded.price, image_url = excluded.image_url,
  description = excluded.description, sizes = excluded.sizes, tag = excluded.tag, rating = excluded.rating, reviews = excluded.reviews;
