// Generates supabase/seed.sql from catalog.js:  node scripts/generate-seed.js
const fs = require("fs");
const path = require("path");
const SEED = require("./catalog-data.js");
const q = (s) => (s == null ? "null" : "'" + String(s).replace(/'/g, "''") + "'");

const sql = `-- Generated by scripts/generate-seed.js. Safe to re-run.
alter table products add column if not exists tag text;
alter table products add column if not exists rating numeric(2,1);
alter table products add column if not exists reviews integer default 0;

alter table orders add column if not exists phone_number text;
alter table orders add column if not exists payment_method text default 'Pay on Delivery';

insert into products (id, name, category, price, image_url, description, sizes, tag, rating, reviews) values
${SEED.map((p) => `(${q(p.id)}, ${q(p.name)}, ${q(p.category)}, ${p.price}, ${q(p.image_url)}, ${q(p.description)}, ${q(JSON.stringify(p.sizes))}::jsonb, ${q(p.tag)}, ${p.rating}, ${p.reviews})`).join(",\n")}
on conflict (id) do update set
  name = excluded.name, category = excluded.category, price = excluded.price, image_url = excluded.image_url,
  description = excluded.description, sizes = excluded.sizes, tag = excluded.tag, rating = excluded.rating, reviews = excluded.reviews;
`;
fs.mkdirSync(path.join(__dirname, "..", "supabase"), { recursive: true });
fs.writeFileSync(path.join(__dirname, "..", "supabase", "seed.sql"), sql);
console.log(`Wrote supabase/seed.sql with ${SEED.length} products`);
